#!/usr/bin/python
import pexpect
import os
# import getpass , os , sys

######################## Instructions & Credits! #####################
####### By Jose A. Salazar
##########################################################

####################### Example ########################################
#### [root@user /]# dfad
#### Instructions and Credits inside This Source Code! Type vi /usr/bin/dfad
#### print ('TYPES CRTL C TO EXIT!!!!!!!')
#### What do you want to delete?: (ENTER FILE OR DIRECTORY NAME)
#########################################################################

######################## What Is Happening ##############################
#### The Scrip updates your computers' database of all of files then locates all of the files and directories which have what you entered when you were prompeted "What do you want to delete?: ". After that it loads all of the files and directories into a new file called "willberemoves.sh" which then is told to output its' output with "rm-rf" infront into another file called "willberemoved.sh". Then "willberemoved.sh" is run as a bash script. The files and directories you created are now deleted. After this the shell scripts are deleted as well.


print ('Instructions and Credits inside This Source Code!  Type vi /usr/bin/dfad')
print ('TYPES CRTL C TO EXIT!!!!!!!')

def removeallonefile():
    what = raw_input("What do you want to delete?: ")
    os.system('updatedb') 
    print ('locate %s >> /tmp/toberemoved.sh' %(what))
    os.system ('locate %s >> /tmp/toberemoved.sh' %(what))
    print ("sed 's/^/rm -rf /' /tmp/toberemoved.sh >> /tmp/willberemoved.sh")
    os.system ("sed 's/^/rm -rf /' /tmp/toberemoved.sh >> /tmp/willberemoved.sh")
    print ('sh /tmp/willberemoved.sh')
    os.system ('sh /tmp/willberemoved.sh')
    print ('rm -rf /tmp/willberemoved.sh /tmp/toberemoved.sh /tmp/toberemoved.sh')
    os.system ('rm -rf /tmp/willberemoved.sh /tmp/toberemoved.sh /tmp/toberemoved.sh')
    os.system ('updatedb')
removeallonefile()
